### ISSUE TITLE
关于“枪手中国球迷社区”的筹建

### ISSUE THREAD

**Issue by nightire** [arsenal-china/arsbbs#1]
@leizhao4 别被我的标题吓到，我承认有点标题党了！:laughing:

实际上只是在 Github 上创建一个 organization 的事儿，现在的 [arsbbs](https://github.com/leizhao4/arsbbs/) 是一个个人项目，而且是私密的。这就意味着所有涉及到增减成员的操作只能由你一个人来负责，不是太利于团队分工协作。

在进入到设计/开发阶段后（现在是筹备阶段），免不了要招募各式各样的人手负责各式各样的工作，所以建立一个 organization 来专注这件事情是很有必要的。有了 organization 就可以有 team 来组织不同类型的工作和人，可以将不同的 project 分配给各自对应的 team，并且 team 内部可以有简单（够用）的权限分配。

因为你是发起人也是现在枪手论坛的主要负责人，所以由你来做 organization 的 owner 是众望所归的事情。organization 的名字我建议用 arsenal-china，之前试了一下还可以用。至于为什么要叫“枪手中国球迷社区”，我在[另外一个 issue](https://github.com/leizhao4/arsbbs/issues/2) 里解释了缘由，你看一下吧。

这事儿你看抽时间处理一下吧，然后你专注的去整理你的想法，我来负责前期的社区建设；进入到下一阶段后，我们再调换角色。

**Comment by leizhao4** [comment]
好的，没问题，那么 repo 还需要 private 吗？我是没什么问题，你决定就好。

**Comment by nightire** [comment]
先不要 private 了，暂时还没有上重要代码的需求，如果以后人多会造成干扰再转 private 好了。

**Comment by leizhao4** [comment]
OK
